
name: CodeBuild

on: [push, pull_request]
jobs:
  build:
    name: Test of the clock-controller.ino compilation for the ESP32 target
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout AsyncTCP library
      uses: actions/checkout@v4
      with:
        repository: ESP32Async/AsyncTCP
        ref: main
        path: CustomAsyncTCP # must contain string "Custom"

    - name: Checkout ESPAsyncWebServer library
      uses: actions/checkout@v4
      with:
        repository: ESP32Async/ESPAsyncWebServer
        ref: main
        path: CustomESPAsyncWebServer # must contain string "Custom"

    - name: Compile sketch
      uses: ArminJo/arduino-test-compile@v3
      with:
        arduino-board-fqbn: esp32:esp32:esp32:PSRAM=disabled,PartitionScheme=default,CPUFreq=240,FlashMode=qio,FlashFreq=80,FlashSize=4M,UploadSpeed=921600,DebugLevel=none
        arduino-platform: esp32:esp32@3.3.11
        platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        sketch-names: marantz.ino
